//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonMart.Data.OldSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string alignment { get; set; }
        public string hit_die { get; set; }
        public string class_skills { get; set; }
        public string skill_points { get; set; }
        public string skill_points_ability { get; set; }
        public string spell_stat { get; set; }
        public string proficiencies { get; set; }
        public string spell_type { get; set; }
        public string epic_feat_base_level { get; set; }
        public string epic_feat_interval { get; set; }
        public string epic_feat_list { get; set; }
        public string epic_full_text { get; set; }
        public string req_race { get; set; }
        public string req_weapon_proficiency { get; set; }
        public string req_base_attack_bonus { get; set; }
        public string req_skill { get; set; }
        public string req_feat { get; set; }
        public string req_spells { get; set; }
        public string req_languages { get; set; }
        public string req_psionics { get; set; }
        public string req_epic_feat { get; set; }
        public string req_special { get; set; }
        public string spell_list_1 { get; set; }
        public string spell_list_2 { get; set; }
        public string spell_list_3 { get; set; }
        public string spell_list_4 { get; set; }
        public string spell_list_5 { get; set; }
        public string full_text { get; set; }
        public string reference { get; set; }
    }
}
