//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonMart.Data.OldSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string cost { get; set; }
        public string dmg_s { get; set; }
        public string armor_shield_bonus { get; set; }
        public string maximum_dex_bonus { get; set; }
        public string dmg_m { get; set; }
        public string weight { get; set; }
        public string critical { get; set; }
        public string armor_check_penalty { get; set; }
        public string arcane_spell_failure_chance { get; set; }
        public string range_increment { get; set; }
        public string speed_30 { get; set; }
        public string type { get; set; }
        public string speed_20 { get; set; }
        public string full_text { get; set; }
        public string reference { get; set; }
    }
}
