//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonMart.Data.OldSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string special_ability { get; set; }
        public string aura { get; set; }
        public string caster_level { get; set; }
        public string price { get; set; }
        public string manifester_level { get; set; }
        public string prereq { get; set; }
        public string cost { get; set; }
        public string weight { get; set; }
        public string full_text { get; set; }
        public string reference { get; set; }
    }
}
