//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonMart.Data.OldSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class power
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string discipline { get; set; }
        public string subdiscipline { get; set; }
        public string descriptor { get; set; }
        public string level { get; set; }
        public string display { get; set; }
        public string manifesting_time { get; set; }
        public string range { get; set; }
        public string target { get; set; }
        public string area { get; set; }
        public string effect { get; set; }
        public string duration { get; set; }
        public string saving_throw { get; set; }
        public string power_points { get; set; }
        public string power_resistance { get; set; }
        public string short_description { get; set; }
        public string xp_cost { get; set; }
        public string description { get; set; }
        public string augment { get; set; }
        public string full_text { get; set; }
        public string reference { get; set; }
    }
}
