//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonMart.Data.OldSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string subtype { get; set; }
        public string key_ability { get; set; }
        public string psionic { get; set; }
        public string trained { get; set; }
        public string armor_check { get; set; }
        public string description { get; set; }
        public string skill_check { get; set; }
        public string action { get; set; }
        public string try_again { get; set; }
        public string special { get; set; }
        public string restriction { get; set; }
        public string synergy { get; set; }
        public string epic_use { get; set; }
        public string untrained { get; set; }
        public string full_text { get; set; }
        public string reference { get; set; }
    }
}
